#
# Makefile for the Qualcomm Technologies Inc EMAC Gigabit Ethernet driver
#

obj-$(CONFIG_MSM_EMAC) += msm_emac.o

msm_emac-objs := emac_main.o emac_hw.o emac_ethtool.o emac_ptp.o
msm_emac-objs += emac_rgmii.o emac_sgmii_v1.o
